### ISSUE TITLE
IceRock KMM #3 "Устройство проекта" -  замечания

### ISSUE THREAD

**Issue by Alex009** [icerockdev/kmm.icerock.dev#23]
- [x] разбор того, что есть из коробки в [mpp-library](https://kmm.icerock.dev/onboarding/project-inside/#mpp-library)
- [x] что есть в [build.gradle](https://kmm.icerock.dev/onboarding/project-inside/#buildgradlekts) и в podfile (чтобы и айосники и андроидщики могли понять всё что есть в проекте) (осталось только про android-app)
- [x] разбор что есть и как устроено в [android-app](https://kmm.icerock.dev/onboarding/project-inside/#android-app)
- [x] разбор что есть и как устроено в [ios-app](https://kmm.icerock.dev/onboarding/project-inside/#ios-app)
- [x] описать про генерацию строк локализации через скрипт с гуглшита (нужно проверить достаточно ли того, что есть) (пока нет в бойлерплейте) -> создан раздел в обучении
- [x] Из каких частей состоит проект
- [x] Где находится конфигурация мультиплатформенного модуля
- [x] Как реализована интеграция мультиплатформенного модуля в iOS
- [x] Какие настройки применены к текущему проекту для мультиплатформенного модуля ( про конфигурации в build gradle kts)
- [x] Как устроена многомодульность на проекте
- [x] Как объявляются внешние зависимости (библиотеки)
- [x] Как настроен экспорт зависимостей в iOS фреймворк
- [x] Как реализован DI (Dependency Injection)
- [x] Как реализована навигация на [android](https://kmm.icerock.dev/onboarding/project-inside/#%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2-android) и [iOS](https://kmm.icerock.dev/onboarding/project-inside/#%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2-ios) (про iOS написано) (переехало в раздел обучения)
- [x] Студия предложила обновить Android Gradle Plugin, какие плагины и зависимости можно обновлять без последствий? (обновлять можно все в принципе, но на мажорных апдейтах (типа AGP 7 или kotlin 1.5.0) есть высокая вероятность что что-то будет несовместимо, поэтому такие апдейты надо делать аккуратно и проверяя что будет с обеими платформами.) -> создан соответствующий раздел в обучении
- [x] В бойлерплейт podfile нужно добавить маппинг конфигураций
- [x] в podfile описать маппинг конфигураций, что это и зачем (ссылка на статью Learning - iOS - Конфигурации)
- [x] в podspec настроить для симулятора компиляцию arm через дополнительные условия -> изменено в рамках boilerplate проекта
- [x] Создадим в ios-проекте папку src/Coordinators исправить на src -> Common -> Coordinator "и создавать нечего не нужно , ведь там уже описание есть"
- [x] Не хватает документирования методов и кода для лучшего восприятия //MARK: и ему подобные. (FelixFalkovsky) (?) (добавлены комментарии в коде)
- [x] Отредактировать статью в местах где говориться что то сделать "Уже сделано!" либо удалить из проекта эти файлы. (FelixFalkovsky) (?) 
- [x] в [Навигация в iOS](https://kmm.icerock.dev/onboarding/project-inside/#%D0%BD%D0%B0%D0%B2%D0%B8%D0%B3%D0%B0%D1%86%D0%B8%D1%8F-%D0%B2-ios) добавить изображения для лучшего понимания 
- [x] предложение: заменить некоторые скриншоты на полные, вместо какой-то области, для наглядности 
- [x] нужно добавить в Deps.kt -> Modules еще варианты, например Entities, Shared ( устарело)
- [x] Добавить что buildSrc больше не используется, ему на смену пришел Versions Catalog

Добавленные статьи в разделе обучения:
Library -> Публикация
Gradle -> Обвноление версий
Gradle -> Build Environment
iOS -> CocoaPods
iOS -> Навигация
Tools -> Генерация строк локализациии

https://kmm.icerock.dev/onboarding/project-inside

**Comment by DevTchernov** [comment]
нужно добавить в Deps.kt -> Modules еще варианты, например Entities, Shared

**Comment by kramlex** [comment]
Добаивть про то, как работают commonMainImplementation() и androidMainImplementation() "работают как buildFlavors?" - commonMainImplementation и подобные работают не как buildFlavors, но похоже в чемто. buildFlavors'ов нет в Kotlin Multiplatform, это фича Android Gradle Plugin'а и все. А в KMM работает Kotlin Gradle Plugin, в котором есть поддержка Hierarhical Multiplatform с множеством source set'ов. и вот для каждого sourceset'а добавляются свои конфигурации для подключения зависимостей к конкретным сорссетам. Сами же сорссеты имеют иерархию, типа как у билдфлейворов. то есть androidMain видит все то что есть в commonMain. а iosArm64 видит все что в iosMain и все что в commonMain. [Читать](https://kotlinlang.org/docs/mpp-dsl-reference.html#source-sets)

**Comment by kramlex** [comment]
Добавить про то, что все мультиплатформенные библиотеки публикуются отдельными артефактами - common, android, iosx64, iosarm64 все это отдельные артефакты - тут наглядно видно что каждая библиотека имеет пачку артефактов
 Написать про это: (В rss-news интерфейс репозитория NewsListRepository лежит в mpp-lib:feature:news:list, а имплементация NewsListRepositoryImpl в mpp-lib:commonMain?) - да, интерфейс получения данных задает сама фича (чтобы уметь получать данные из вне). А реализация находится в mpp-library, в которой доступны классы всех фичей и происходит связывание всех компонентов воедино

**Comment by kramlex** [comment]
В пункте 5 в главе "Компиляция MultiPlatformLibrary.framework" можно немного пояснить что такое компиляция kotlin модуля. Мол, эта задача запускает компилятор Kotlin Native, который компилирует common и ios код в нативную статическую библиотеку, которая упаковывается в статический фреймворк вместе с ресурсами модуля, который и подключается к проекту xcode.

**Comment by kramlex** [comment]
Добавить про то, что все мультиплатформенные библиотеки публикуются отдельными артефактами - common, android, iosx64, iosarm64 все это отдельные артефакты - тут наглядно видно что каждая библиотека имеет пачку артефактов

**Comment by kramlex** [comment]
Описать, как "Gradle съел кастом GradlePlugin класс в plugins { plugin(Deps.Plugins.androidApplication) }" (GradlePlugin класс приходит из mobile-multiplatform-plugin и в том же файле видно что для классов управления зависиомостями гредла добавлена функция plugin которая умеет принимать GradlePlugin)

**Comment by kramlex** [comment]
Добавить что buildSrc больше не используется, ему на смену пришел Versions Catalog
